services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - movies
      - rails



  movies:
    container_name: backend
    build:
      context: ./movies
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    env_file:
      - .env
  



  rails:
    build: ./auth
    # ports:
      # - "8001:8001"
    volumes:
      - ./auth:/app
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
      - GOOGLE_SMTP_USERNAME=${GOOGLE_SMTP_USERNAME}
      - GOOGLE_SMTP_PASSWORD=${GOOGLE_SMTP_PASSWORD}
    depends_on:
      - postgres
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #     - WEBUI_PORT=8080
  #     - QBITTORRENT_WEBUI_USERNAME=admin
  #     - QBITTORRENT_WEBUI_PASSWORD=adminadmin
  #     - INSTALL_PYTHON3=true
  #   volumes:
  #     - ./qbittorrent/config:/config
  #     - ./movies/video_test:/downloads
  #   ports:
  #     - 8080:8080
  #     - 6881:6881
  #     - 6881:6881/udp
  #   restart: unless-stopped

  # jackett:
  #   image: lscr.io/linuxserver/jackett:latest
  #   container_name: jackett
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - ./jackett/config:/config
  #   ports:
  #     - "9117:9117"
  #   restart: unless-stopped