events {}

http {
  upstream movies_backend {
    server movies:8000;
  }
  upstream rails_backend {
    server rails:8001;
  }

  server {
    listen 80;

    location /auth/ {
      proxy_pass http://rails_backend/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://movies_backend/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}